export const shippingData = [
  {
    id: '1',
    from: 'Cairo',
    to: 'Alexandria',
    shippmentID: '12345678901',
    status: 'RECEIVED',
    addressFrom: 'Doki, 22 Nile Street',
    addressTo: 'Smoha, 22 Max Street',
    name: 'John Doe',
  },
  {
    id: '2',
    from: 'New York',
    to: 'Los Angeles',
    shippmentID: '12345678902',
    status: 'RECEIVED',
    name: 'Alice Smith',
    addressFrom: 'NYC, 123 Broadway',
    addressTo: 'LA, 456 Hollywood Blvd',
  },
  {
    id: '3',
    from: 'London',
    to: 'Paris',
    shippmentID: '12345678903',
    status: 'DELIVERED',
    name: 'Bob Johnson',
    addressFrom: 'London Bridge, 7 Thames St',
    addressTo: 'Eiffel Tower, 10 Champs-Élysées',
  },
  {
    id: '4',
    from: 'Berlin',
    to: 'Madrid',
    shippmentID: '12345678904',
    status: 'ERROR',
    name: 'Emily Brown',
    addressFrom: 'Berlin Wall, 15 East Side',
    addressTo: 'Plaza Mayor, 20 Calle Mayor',
  },
  {
    id: '5',
    from: 'Tokyo',
    to: 'Seoul',
    shippmentID: '12345678905',
    status: 'CANCELED',
    name: 'David Wilson',
    addressFrom: 'Tokyo Tower, 100-0001 Tokyo',
    addressTo: 'Gyeongbokgung Palace, 161 Sajik-ro',
  },
  {
    id: '6',
    from: 'Sydney',
    to: 'Melbourne',
    shippmentID: '12345678906',
    status: 'ON HOLD',
    name: 'Emma Lee',
    addressFrom: 'Opera House, Bennelong Point',
    addressTo: 'Melbourne Central, 211 La Trobe St',
  },
  {
    id: '7',
    from: 'Paris',
    to: 'London',
    shippmentID: '23456789012',
    status: 'RECEIVED',
    name: 'James Smith',
    addressFrom: 'Champs-Élysées, 10 Eiffel Tower',
    addressTo: 'London Bridge, 7 Thames St',
  },



];
